Premium support container image upgrades
airbytehq/airbyte-platform pull request #240
Opened 2023-05-20 00:55 UTC by peterth3

## What
*Describe what the change is solving*
Upgrades dependencies for several docker images and switches to alpine to improve image footprint and security.

## How
*Describe the solution*

Switches base images to alpine wherever possible and changes dependency installs from `yum` to `apk`.

## Recommended reading order
n/a

## Can this PR be safely reverted / rolled back?
*If you know that your PR is backwards-compatible and can be simply reverted or rolled back, check the YES box.*

*Otherwise if your PR has a breaking change, like a database migration for example, check the NO box.*

*If unsure, leave it blank.*
- [ x] YES 💚
- [ ] NO ❌

## 🚨 User Impact 🚨
Are there any breaking changes? What is the end result perceived by the user? If yes, please merge this PR with the 🚨🚨 emoji so changelog authors can further highlight this if needed.

Not to our knowledge. We are running these alpine-based images in our cluster without issues.

2023-05-22 15:33 UTC, marcosmarxm commented
Thanks for the contribution @peterth3 I requested to our engineer team to take a look in your contribution.

2023-05-22 15:45 UTC, marcosmarxm requested changes
I am doing the first review, @peterth3, but we must wait for the engineering team's review and their considerations.

2023-05-22 15:45 UTC, marcosmarxm commented on airbyte-workers/build.gradle
> +        force libs.flyway.core, libs.jooq, libs.s3, libs.aws.java.sdk.s3, libs.jsonsmart
Any particular reason to add `jsonsmart` lib?

2023-05-22 15:45 UTC, marcosmarxm commented on airbyte-webapp/Dockerfile
> +#    adduser -S appuser -G appgroup -u 1000 \
Can you remove the comments?

2023-05-22 15:45 UTC, marcosmarxm commented on airbyte-container-orchestrator/Dockerfile
> +#RUN yum install -y jq tar && yum clean all
Remove the comments.

2023-05-22 16:57 UTC, mauricioalarcon commented on airbyte-workers/build.gradle
> +        force libs.flyway.core, libs.jooq, libs.s3, libs.aws.java.sdk.s3, libs.jsonsmart
yes, the provided version has know vulnerabilities, so we bumped it and force it here. 

https://nvd.nist.gov/vuln/detail/CVE-2023-1370

2023-05-23 18:05 UTC, davinchia commented
the security changes here look sane to me, @wennergr can you confirm?

2023-05-25 21:25 UTC, davidmhleung commented
@davinchia , @wennergr - Any update on this?

2023-05-31 00:12 UTC, davidmhleung commented
@marcosmarxm - requested changes have been updated.

2023-05-31 01:15 UTC, marcosmarxm commented
> @marcosmarxm - requested changes have been updated.

I'm going to take a look tomorrow @davidmhleung

2023-06-02 18:13 UTC, peterth3 commented
Thank you @marcosmarxm 

We need to resolve image vulnerabilities to run Airbyte in our environment. Here's the latest security scan on ArtifactHub ("F"), which aligns with the results we're seeing from our internal scanner. Switching to alpine and upgrading auto-temporal resolved the majority of these vulnerabilities on our end.

https://artifacthub.io/packages/helm/airbyte/airbyte
![Screenshot 2023-06-02 at 9 44 49 AM](https://github.com/airbytehq/airbyte-platform/assets/9690235/9daceb29-6b65-451a-a4bd-4396b169b4f8)

2023-06-05 13:40 UTC, marcosmarxm requested changes
> Thank you @marcosmarxm
> 
> We need to resolve image vulnerabilities to run Airbyte in our environment. Here's the latest security scan on ArtifactHub ("F"), which aligns with the results we're seeing from our internal scanner. Switching to alpine and upgrading auto-temporal resolved the majority of these vulnerabilities on our end.
> 
> https://artifacthub.io/packages/helm/airbyte/airbyte ![Screenshot 2023-06-02 at 9 44 49 AM](https://user-images.githubusercontent.com/9690235/242943566-9daceb29-6b65-451a-a4bd-4396b169b4f8.png)

Understood. But today uprading temporal won't work without doing changes to Airbyte code first to make compatible.
Can we proceeded as described in the email: upgrade the packages and addition of `jsonsmart` library.

2023-06-20 01:59 UTC, merged